language: objective-c
osx_image: xcode7.2
script:
- set -o pipefail
- xcodebuild -list
- xcodebuild -scheme HRTime test -sdk macosx -enableCodeCoverage YES -derivedDataPath ./out | xcpretty 
- xcrun llvm-cov report -use-color=true -instr-profile ./out/Build/Intermediates/CodeCoverage/HRTime/Coverage.profdata ./out/Build/Intermediates/CodeCoverage/HRTime/Products/Debug/HRTime.framework/HRTime
